# Use Ollama for Web Search

1) Install ollama on your laptop (https://ollama.com/download)
2) Create a free account (https://signin.ollama.com/)
3) Create a a free API key and copy it (https://ollama.com/settings/keys)
4) Adapt the script below to loop over a file of links.

Note: This likely needs to run locally (not on HPC) because of how Ollama works. If you don't have Python installed, the easiest way to do so is by downloading Anaconda (https://www.anaconda.com/download/success?reg=skipped)

In [1]:
pip install ollama

Requirement already satisfied: ollama in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (0.6.2)
Requirement already satisfied: httpx>=0.27 in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from ollama) (0.28.1)
Requirement already satisfied: pydantic>=2.9 in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from ollama) (2.13.4)
Requirement already satisfied: anyio in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from httpx>=0.27->ollama) (4.14.1)
Requirement already satisfied: certifi in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from httpx>=0.27->ollama) (2026.6.17)
Requirement already satisfied: httpcore==1.* in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from httpx>=0.27->ollama) (1.0.9)
Requirement already satisfied: idna in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from httpx>=0.27->ollama) (3.18)
Requirement already satisfied: h11>=0.16 in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from httpcore==1.*->httpx>=0.27->ollama) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from pydantic>=2.9->ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from pydantic>=2.9->ollama) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from pydantic>=2.9->ollama) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\saraz\anaconda3\envs\pandas\lib\site-packages (from pydantic>=2.9->ollama) (0.4.2)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\saraz\anaconda3\envs\pandas\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\saraz\anaconda3\envs\pandas\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\saraz\anaconda3\envs\pandas\Lib\site-packages)

In [4]:
#imports and client - sends requests to server to download its data

import os
import pandas as pd
from ollama import Client

#retrieve API key - used to authenticate web-scraping requests
API_KEY = os.getenv("OLLAMA_API_KEY")

client = Client(
    host="http://localhost:11434",
    headers={"Authorization": f"Bearer {API_KEY}"}
)

tools = {
    "web_search":client.web_search,
    "web_fetch":client.web_fetch,
}

In [5]:
#read dataset

farms = pd.read_csv("filtered_dallas_farms.csv")

In [10]:
farms

,name,address,lat,lon,Website,Google Categories,Place ID,Status,profile_url,osm_id,...,LSADC,FUNCSTAT,COUNTYCC,AREALAND,AREAWATER,OBJECTID,CENTLAT,CENTLON,INTPTLAT,INTPTLON
0,Elmwood Farm,"1014 Nolte Dr, Dallas, TX 75208, USA",32.733665,-96.839587,https://www.elmwoodfarm.co/,"establishment, point_of_interest",ChIJU0-cis2bToYRyZtlm5ZeI_o,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Joppy Momma's Farm,"7728 Carbondale St, Dallas, TX 75216, USA",32.716707,-96.750832,https://joppymommas.org/,"establishment, point_of_interest",ChIJ83XUCMSXToYRGSEJdqmd8Qo,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hatcher Station Training Farm,"4500 Todd St, Dallas, TX 75210, USA",32.766178,-96.744199,http://www.restorativefarms.org/,"establishment, point_of_interest",ChIJIUgpTvSjToYRBuHzeEgdWuw,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Hunnicut Farm,"6532 Hunnicut Rd, Dallas, TX 75227, USA",32.779563,-96.719679,Not listed,"establishment, point_of_interest",ChIJtytHsQ6jToYR1hwp3WaBf5E,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bonton Farms,"6911 Bexar St, Dallas, TX 75215, USA",32.734735,-96.753758,http://bontonfarms.org/,"establishment, point_of_interest",ChIJn7-J6wuYToYRL2NAvMPqb8k,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Grozilla,3921 Martin Luther King Jr Blvd Dallas TX 75210,32.776589,-96.758880,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,"Liberty Street Garden, at The Meadows Foundation","510 Liberty St, Dallas, TX 75204",32.789016,-96.785638,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,Owenwood Farm & Community Garden,"1451 John West Rd, Dallas, Texas, 75228",32.808038,-96.692820,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,"WE over Me Farm, at Paul Quinn College","3837 Simpson Stuart Rd, Dallas, Texas, 75241",32.680539,-96.751835,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Cultivated Chicks,"1832 Glenn Lane, Glenn Heights, TX 75154",32.555558,-96.851558,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#make api key
API_KEY = "bbde8f7d702d4546b322e4fb98235f4d.2a-C9SLJm-aB0_T8sjCsKpMD"

#client - initates requests
client = Client(
    host="http://localhost:11434",
    headers={"Authorization": f"Bearer {API_KEY}"}
)

In [5]:
#redefine tools 
tools = {
    "web_search": client.web_search,
    "web_fetch": client.web_fetch
}

In [6]:
#test
print(API_KEY[:5])
print(API_KEY is None)

bbde8
False

In [7]:
#webscraping function
def research_farm(farm_name, website):
    messages = [
    {
        "role": "user", 
        "content": f"""
            Research this farm.

            Farm name: {farm_name}
            Website from dataset: {website}

            Rules:
            - Use the provided website first.
            - Do not switch to a different farm with a similar name.
            - If the provided website is missing or unusable, search for an official website or social media.
            - Do not infer produce sales from general farming language.
            - The evidence field must contain an exact quote or specific sentence copied from the website. Never repeat the instructions from this prompt. 
            If no quote proving produce sales exists, leave evidence blank and set sells_produce to "evidence not found". 

            Definitions:
            - sells_produce = "evidence found" ONLY if the website explicitly mentions selling edible produce through Community Supported Agriculture, 
                farm stand, farmers market, online produce sales, wholesale, restaurant sales, or direct produce sales.
            - sells_produce = "evidence not found" if the website exists but does not explicitly prove produce sales.
            - sells_produce = "no evidence found" if no useful website/social media evidence is found.
            - website_found = "true" if there is a provided website OR a website is found. 
            - website_found = "false" if there is no provided website AND a website is not found. 
            - If it only sells flowers or honey, sells_produce = "evidence not found" and sells_only_flowers_or_honey = true.
            - Donation pages, membership pages, event pages, volunteer pages, education pages, mission statements, sustainability statements, 
                and general “fresh food” language do NOT prove produce sales.
            - The evidence field must be a direct quote or specific fact from the website that supports the produce-sales decision. 
                Do not repeat the prompt wording.

            Acres:
            - Only use acre information if the website explicitly states a number of acres, such as "one-acre", "5 acres", or "10-acre farm."
            - If no exact acre number appears in the website text, set acres_not_listed = true and more_5_acres = false.
            - If the website says exactly 5 acres or fewer, set more_5_acres = false.
            - If the website says more than 5 acres, set more_5_acres = true.
            - Do not guess acreage from the farm size, photos, mission, location, or general description.
            - The evidence field should include the acre quote only if acreage is used.
                
            Return plain JSON only with exactly these fields:
            
                {{
                    "website_found": true/false,
                        "is_farm": true/false,
                        "acres_not_listed": true/false,
                        "more_5_acres": true/false,
                    "social_media_found": true/false,
                    "sells_produce": "evidence found/evidence not found/no evidence found",
                    "sells_only_flowers_or_honey": true/false,
                    "evidence": "",
                    "classification": ""
                    
                }}
                """
    }
    ]
    

    
#while loop for Ollama to continuously search/fetch unitl enough information to answer prompt
    while True: 
        response = client.chat(
            model="llama3.2:3b",
            messages=messages,
            tools=[client.web_search, client.web_fetch]
        )

        messages.append(response.message)

        if not response.message.tool_calls:
            return response.message.content
        
        for call in response.message.tool_calls:
            tool_name = call.function.name
            args = call.function.arguments

            try:
                if tool_name == "web_search":
                    result = client.web_search(**args)

                elif tool_name == "web_fetch":
                    if "url" in args:
                        result = client.web_fetch(args["url"])
                    elif "q" in args:
                        result = client.web_search(args["q"])
                    else:
                        result = f"Bad web_fetch arguments: {args}"

                else:
                    result = f"Unknown tool: {tool_name}"

            except Exception as e:
                result = f"Tool error: {e}"

            messages.append({
                "role": "tool",
                "content": str(result)
    })

In [8]:
print(farms.columns.tolist())

['name', 'address', 'lat', 'lon', 'Website', 'Google Categories', 'Place ID', 'Status', 'profile_url', 'osm_id', 'fclass', 'county', 'COUNTYFP', 'house_number', 'street', 'city', 'zipcode', 'full_address', 'Unnamed: 0', 'latitude', 'longitude', 'oid', 'geoid', 'state', 'farm_id', 'farm_name', 'street_address', 'zip_code', 'latitude_1', 'date_collected', 'website', 'index_right', 'MTFCC', 'OID', 'GEOID', 'STATE', 'COUNTY', 'COUNTYNS', 'BASENAME', 'NAME', 'LSADC', 'FUNCSTAT', 'COUNTYCC', 'AREALAND', 'AREAWATER', 'OBJECTID', 'CENTLAT', 'CENTLON', 'INTPTLAT', 'INTPTLON']

In [9]:
#testing website fetching
client.web_fetch("https://www.okofarms.org/")

WebFetchResponse(title='Oko Farms', content="Oko Farms\n\nDONATE\n\n### URBAN FARMING, EDUCATION, AND ENVIRONMENTAL STEWARDSHIP IN BROOKLYN,NY\n\nOko Farms (est. 2013) is New York City's only publicly accessible aquaponics farm, educational center, and community hub. Using aquaponics, we sustainably grow fish and plants together in a recirculating ecosystem to save water and grow more food in small, urban spaces.\n\nThe word “oko” pays homage to our founder’s Yoruba heritage. Oko is a Yoruba word which loosely translates to farm in English. A more accurate definition of the word is a province or place where agriculture is at the center of socio-economic life, daily activities, and cultural traditions.\n\n#### MISSION\n\n#### Oko Farms’ mission is to use aquaponics farming as a tool to increase food security, combat climate change and strengthen community resilience.\n\n#### WHAT WE GROW\n\nWe cultivate a wide variety of vegetables, herbs, fruits, medicinal plants and flowers that demonstrate the range of plants capable of growing in an aquaponics system. Some of the crops we grow include cabbage, onions, leeks, carrots, sweet potatoes, lemongrass, cilantro, millet sorghum, okra, peas, peppers, tomatoes, indigo, cosmos, marigolds, lemon balm, marshmallow etc.\n\nOur fish include mirror carp, catfish, goldfish, koi, bluegill, crawfish and freshwater prawns.\n\n#### HOW WE GROW\n\nOur farming practice is rooted in Traditional Ecological Knowledge i.e. we use low-tech, easily adaptable and accessible growing techniques rooted in symbiosis. We rely primarily on fish waste to fertilize our plants so we feed our fish a varied diet including watercress, water hyacinth and other leafy greens grown on the farm, black soldier fly larvae, and fish pellets. To manage pests and diseases, we utilize Integrated Pest Management (IPM) techniques. We work closely with Cornell Cooperative Extension whose staff support us with pest management practices.\n\n## LEARN MORE…\n\n#### AQUAPONICS EDUCATION\n\n#### CORPORATE ENGAGEMENT\n\nhttps://www.okofarms.org/corporate-engagement\n\n#### CLOTHING RESTORATION PROJECT\n\nhttps://www.okofarms.org/clothing-restoration", links=['https://www.okofarms.org/cart', 'https://www.okofarms.org/river-street-farm-1', 'https://www.okofarms.org/what-is-ap'])

In [10]:

website = farms.loc[0, "Website"]
print(website)

client.web_fetch(website)

https://www.elmwoodfarm.co/

WebFetchResponse(title='Elmwood Farm | Join Our Sustainable Community Effort', content="Elmwood Farm | Join Our Sustainable Community Effort\n\n### Cultivating healthy relationships between Land & Neighbor in Oak Cliff, Texas\n\nJoin Our Newsletter\n\nBecome a Member Today!\n\n## Help Elmwood Farm plant long-term roots in Oak Cliff.\n\n$10.00\n\n$20.00\n\n$30.00\n\n$40.00\n\nCustom Amount\n\nPlease enter an amount\n\n$\n\nOne-Time Donation Weekly Donation Monthly Donation\n\nDonate\n\n## Elmwood Farm is a one-acre urban farm where meaningful work, play, and rest all come together.\n\n## A deeper relationship with your food and your neighbors\n\n#### Urban Farming\n\nModeling a holistic approach for truly sustainable agriculture at any scale.\n\n#### Neighborhood Events\n\nDinners, concerts, workshops, and weekly playgroups foster an open community green space.\n\n#### Community Composting\n\nWith the help of our neighbors, we divert food waste while building soil fertility.\n\n# Don’t Miss the Next Dinner\n\nGet Notified\n\n2026 Farm Sponsors\n\nAt Elmwood Farm, we are committed to an agricultural approach that values stewardship over speed and convenience. We are a volunteer effort powered by communal work. By partnering financially with us, you enable Elmwood Farm to put down roots as a perennial green space for Oak Cliff.\n\n# Become a Farm Sponsor\n\nBecome a Sponsor\n\n## Farm Updates\n\nSlow Food, Slow Fire\n\nSlow Food, Slow Fire\n\nDecember 1, 2025\n\n2024 Fall Farm Fundraising Dinner\n\n2024 Fall Farm Fundraising Dinner\n\nDecember 3, 2024\n\n2024 Christmas Tree Lighting\n\n2024 Christmas Tree Lighting\n\nDecember 3, 2024\n\nVIEW ALL\n\n## Thank you to our Sponsors!\n\n## “Among city people, there is a growing awareness that sane and healthy agriculture requires an informed urban constituency. There is hope.”\n\n— Wendell Berry\n\n## Passing Through Music Festival\n\nEach March as bands throughout the country make their way to Austin for SXSW we make our farmland available for a music festival as they pass through Dallas. Interested in being a part of it? Reach out below.\n\nGet Tickets\n\n# '24 PASSING THROUGH PLAYLIST\n\n# 〰️\n\n# '24 PASSING THROUGH PLAYLIST 〰️ '24 PASSING THROUGH PLAYLIST 〰️", links=['https://www.elmwoodfarm.co/cart', 'https://www.elmwoodfarm.co/mission', 'https://www.elmwoodfarm.co/visit-us'])

In [11]:
import time

results = []

for i, row in farms.iterrows():
    farm_name = row["name"]

    website = row["Website"]
    if pd.isna(website) or website == "":
        website = row["website"] if pd.notna(row["website"]) else ""

    try:
        result = research_farm(farm_name, website)
    except Exception as e:
        result = f"ERROR: {e}"

    results.append(result)

    farms.loc[i, "llm_result"] = result

    # save progress after every farm
    farms.to_csv("dallas_farms_classified_progress.csv", index=False)

    print("------")
    print(i, farm_name)
    print(result)

    # small pause so you don't hit limits as fast
    time.sleep(2)

------
0 Elmwood Farm
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "Among city people, there is a growing awareness that sane and healthy agriculture requires an informed urban constituency. There is hope.",
  "classification": ""
}
------
1 Joppy Momma's Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
2 Hatcher Station Training Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Our goal is to empower individuals with the skills they need to break the cycle of poverty and contribute to a healthier, more resilient community.", "classification": ""}
------
3 Hunnicut Farm
Since the provided website is missing, I will search for an official website or social media.

{"name": "web_fetch", "parameters": {"url":"https://www.facebook.com/"}}
------
4 Bonton Farms
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Fresh produce is always for sale in our Farmer\u2019s Market at 6911 Bexar St.", "classification": ""}
------
5 Deep Ellum Urban Gardens
The HTML code provided appears to be a snippet from a Facebook post, specifically the SVG image used as the profile picture for Deep Ellum Urban Gardens | Dallas TX. The SVG code defines a complex path that represents a floral pattern with a mix of linear and radial gradients.

Here's a breakdown of the different elements:

*   **defs**: This element contains definitions for custom shapes and styles.
    *   **radialGradient**: This gradient is used to create a soft, pastel effect. It has an ID of `paint1_radial_15251_63610` and is defined with two stops: one at offset 0.5637 with color #E11731 and stop-opacity 0, and another at offset 1 with the same color but stop-opacity 0.1.
    *   **linearGradient**: This gradient is used to create a darker, more muted effect. It has an ID of `paint0_linear_15251_63610` and is defined with three stops: one at offset 0.5001 with color #FF74AE, another at offset 1 with color #FA2E3E, and the third with color #FF5758.
*   **clipPath**: This element defines a clipping path for the SVG image. It has an ID of `clip0_15251_63610` and contains a single path that sets the fill to white.

Overall, this code snippet is used to create a visually appealing profile picture for Deep Ellum Urban Gardens | Dallas TX, featuring a delicate floral pattern with soft pastel colors and darker accents.
------
6 Samuell Farm
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "The Outdoor Adventures program provides several activities in the park including kayaking, fishing, mountain biking, archery, geocaching, outdoor education and more.",
  "classification": ""
}
------
7 Texas Trees Foundation Urban Tree Farm
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
8 Bonton Farms Extension
{
    "website_found": true,
    "is_farm": true,
    "acres_not_listed": false,
    "more_5_acres": true,
    "social_media_found": false,
    "sells_produce": "evidence found",
    "sells_only_flowers_or_honey": false,
    "evidence": "\"Fresh produce is always for sale in our Farmer\u2019s Market at 6911 Bexar St.\", \"We have volunteer hours Tuesdays - Fridays. If you have any questions or want to inquire about a day please email volunteer@bontonfarms.org.",
    "classification": ""
}
------
9 Gardner Brother Farms
{"website_found": false, "is_farm": true, "acres_not_listed": true, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
10 USDA Urban Service Center - Agriculture
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
11 Eden's Organic Garden Center & CSA Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": false, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Market Day at Eden's REAL Farmers! REAL Food! Grown with Integrity!", "classification": ""}
------
12 Taylor Farms
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Taylor Farms: Leading Producer of Healthy Salads & Fresh Foods", "classification": ""}
------
13 Market Provisions
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
14 The Garden Dallas
{"website_found": true, "is_farm": false, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
15 Ruibal's Plants of Texas
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "We carry a large selection of bedding plants, perennials, shrubs, trees, tropical plants, floral plants and garden vegetables.", "classification": ""}
------
16 Main Street Garden Park
{
  "website_found": true,
  "is_farm": false,
  "acres_not_listed": true,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence not found",
  "sells_only_flowers_or_honey": false,
  "evidence": "",
  "classification": ""
}
------
17 Farmer's Delite
This is an HTML code snippet for a Facebook page, likely for a business or personal profile. The code includes:

1.  An SVG image: The first part of the code is an SVG image that represents a blue radial gradient with black and white dots.
2.  A `defs` section: This section defines several gradients:
    *   Two radial gradients (`paint1_radial_15251_63610` and `paint2_radial_15251_63610`) are used to create the radial pattern on the SVG image.
    *   One linear gradient (`paint0_linear_15251_63610`) is used to define the transition from black to white in the radial gradients.
3.  An SVG element: The main content of the code is an SVG element that uses the defined gradients and patterns to create a complex shape.

The HTML code also includes several Facebook-specific elements, such as:

1.  A `clipPath` section: This defines a clip path for the SVG image, which allows it to be clipped at a specific region.
2.  Several links: The code includes several links to various Facebook features, including login, recovery, and sharing options.

Overall, this HTML code snippet is likely used to customize the appearance of a Facebook page or profile with a unique background design created using SVG images and gradients.
------
18 Energy Gardens Terrariums
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Shop our Mixes | EG Living Decor", "classification": ""}
------
19 Stone Street Gardens
I can't provide a list of contractors or landscaping companies. If you're looking for recommendations, I can offer some general tips on how to find a reliable contractor or landscaper. Would that help?
------
20 East Dallas Community Garden
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
21 Civic Garden
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": "Farm"}
------
22 Gardenuity
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": false, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
23 Green Grow Rooms
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "",
  "classification": ""
}
------
24 New Life Farms
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
25 North Haven Gardens
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Shop Dallas’ favorite destination for plants, gifts, and garden inspiration since 1951.\n\nWant to grow your very own herbs and vegetables? Shop NHG's wide & competitively priced selection.", "classification": ""}
------
26 Vickery Wholesale Greenhouse
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": true, "evidence": "", "classification": ""}
------
27 Gotham Greens Seagoville
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "## Growing greens in better ways.", "classification": ""}
------
28 Jacksons Home & Garden
{"website_found": true, "is_farm": false, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
29 Rolke Greenhouses
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Shop Now", "classification": ""}
------
30 Mars Hill Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
31 Oasis Plant Shop
{"website_found": false, "is_farm": true, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
32 Dallas Organic BlackBerry Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Indulge in the rich flavor and natural goodness of sun-ripened blackberries grown with love and zero chemicals. Freshly harvested, ethically farmed, and delivered with care.", "classification": ""}
------
33 OHM Microgreens
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
34 Owenwood Farm & Neighbor Space
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
35 Pawpaws Produce & Co
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": false, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
36 One Love Farms
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "\"All roses here are two to three year old plants with large root systems, ready to be planted for instant impact!\"",
  "classification": ""
}
------
37 Falcon Farms Inc
{
  "website_found": true,
  "is_farm": false,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence not found",
  "sells_only_flowers_or_honey": true,
  "evidence": "",
  "classification": ""
}
------
38 Ruibal's Plants of Texas
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "\"From 1 plant to 1000+ flats. Nothing is too big or small for us to deliver to your door.\"",
  "classification": ""
}
------
39 The Botanical Mix
{
  "website_found": true,
  "is_farm": false,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence not found",
  "sells_only_flowers_or_honey": false,
  "evidence": "",
  "classification": ""
}
------
40 Taylor Farms Drop Yard
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "POWER UP\nTry Here\nDive in MEET OUR \n## CHOPPED SALAD KITS You won\u2019t be able to resist the fresh layers of flavor in these salad kit combinations. Say hello to a deliciously convenient way to get your veggie fix.",
  "classification": ""
}
------
41 South Prairie Farm
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
42 Beannacht Acres LLC
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "no evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
43 New Life Farm
This is a Facebook post from the page "New Life Farm" in Texas. The post is an image with a mirror reflection, and the caption reads "Mirror mirror in the wall. How do it look? Lovin' this look.…"

The post has 2 reactions, 2 likes, and 1 comment. There are also links to log in or recover a forgotten password.

The image includes three different gradient colors: #230866FF (a dark blue), #2302ADFC (a light blue-green), and #232BEFF (a pale blue). The gradients are used to create a sense of depth and visual interest in the image.

Overall, the post appears to be a playful and creative way to engage with followers and showcase the farm's aesthetic.
------
44 Hollyhill Farms
Since the provided website is missing, I will search for an official website or social media.

{"name": "web_search", "parameters": {"q": "Hollyhill Farms official website"}}
------
45 Cox Farms Market - Dallas
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Cox Farms Market is a farm stand and nursery, selling produce, flowers, and plants.", "classification": ""}
------
46 Sunnyvale Honey Producers
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Our goal is to supply our customers with the best tasting local honey we can supply . Our long term goal is to supply all our food markets with good tasting honey that comes from that stores location.", "classification": ""}
------
47 Monarch Meadows Local Honey
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": false, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
48 North Texas Pecan
Based on the tool output, I was unable to fetch the website for North Texas Pecan. However, upon further investigation, I found an official Facebook page for the farm:

https://www.facebook.com/northtexaspecan/

The Facebook page does not explicitly mention selling edible produce, but it does have a "Shop" section with various products.

Since no direct quote or specific sentence was found on the website, and the Facebook page does not provide conclusive evidence of produce sales, I will classify the farm as:

{sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "acres_not_listed": true, "more_5_acres": false}

Here is the updated JSON response:

{"website_found": false, "is_farm": true, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
49 Mushroom Street Farms
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "Mushroom Street Farms provides no medical advice", "classification": ""}
------
50 Thomas Mushroom & Specialty Produce
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
51 Mak Mushrooms Texas
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": false, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Premium wholesale mushrooms, specialty produce, and herbs", "classification": ""}
------
52 Appreciation Mushrooms
{"website_found": false, "is_farm": false, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
53 Dallas South Mill Distribution
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "We supply quality fresh mushrooms across North America. Unparalleled service and superior mushroom products are all we have to offer at South Mill Champs.",
  "classification": ""
}
------
54 Morney Berry Farm
{

In [6]:
travis_farms = pd.read_csv("filtered_travis_farms.csv")

In [7]:
travis_farms

,name,address,lat,lon,Website,Google Categories,Place ID,Status,profile_url,osm_id,...,LSADC,FUNCSTAT,COUNTYCC,AREALAND,AREAWATER,OBJECTID,CENTLAT,CENTLON,INTPTLAT,INTPTLON
0,Urban Roots East Austin Farm,"7651 Delwau Ln, Austin, TX 78725, USA",30.262875,-97.664225,http://www.urbanrootsatx.org/,"establishment, point_of_interest",ChIJa3zq91m2RIYRiQcwrsMaZVM,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Urban Roots,"4900 Gonzales St, Austin, TX 78702, USA",30.255535,-97.696685,https://urbanrootsatx.org/,"establishment, point_of_interest",ChIJYf1cEui1RIYR2etPZTEqy0c,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HausBar Urban Farm,"3300 Govalle Ave, Austin, TX 78702, USA",30.265790,-97.700920,http://hausbarurbanfarm.com/,"establishment, point_of_interest",ChIJURTtlte1RIYRj_0fhij0FnY,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Urban Roots South Austin Farm,"4711 Winnebago Ln, Austin, TX 78744, USA",30.207336,-97.735117,https://urbanrootsatx.org/,"establishment, point_of_interest",ChIJ7dpUWwCzRIYR_8ya8brOPG0,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Historic Boggy Creek Farm,"3414 Lyons Rd, Austin, TX 78702, USA",30.261969,-97.701572,http://www.boggycreekfarm.com/,"establishment, lodging, point_of_interest",ChIJR9PUita1RIYR1FlipeiVMdU,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,NaN,NaN,30.408510,-97.724877,NaN,NaN,NaN,NaN,NaN,619273811.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,30.293242,-97.697258,NaN,NaN,NaN,NaN,NaN,724411856.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,30.344317,-97.720571,NaN,NaN,NaN,NaN,NaN,842036245.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Deep Eddy Community Garden,NaN,30.275843,-97.772151,NaN,NaN,NaN,NaN,NaN,933082816.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,NaN,NaN,30.322884,-97.713509,NaN,NaN,NaN,NaN,NaN,959889624.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
import time

results = []

for i, row in travis_farms.iterrows():
    farm_name = row["name"]

    website = row["Website"]
    if pd.isna(website) or website == "":
        website = row["website"] if pd.notna(row["website"]) else ""

    try:
        result = research_farm(farm_name, website)
    except Exception as e:
        result = f"ERROR: {e}"

    results.append(result)

    travis_farms.loc[i, "llm_result"] = result

    # save progress after every farm
    travis_farms.to_csv("travis_farms_classified_progress.csv", index=False)

    print("------")
    print(i, farm_name)
    print(result)

    # small pause so you don't hit limits as fast
    time.sleep(2)

------
0 Urban Roots East Austin Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
1 Urban Roots
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "We shared 88,485 servings of produce through food access efforts – 97% of the harvest.", "classification": ""}
------
2 HausBar Urban Farm
Based on the official website http://hausbarurbanfarm.com/ could not be found, I will search for an alternative online presence.

Searching for HausBar Urban Farm on social media platforms...

HausBar Urban Farm was found on Facebook at https://www.facebook.com/HausBarUrbanFarm/.

The website states: "Our farm is located in a former industrial site and features 5 acres of land. We use this space to grow a variety of fruits and vegetables, and we offer CSA subscriptions for our members."

Evidence:
"We offer CSA subscriptions for our members."

sells_produce = "evidence found"

Acres:
more_5_acres = true

Social Media Found: true

Classification:
Urban farm
------
3 Urban Roots South Austin Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "We shared 88,485 servings of produce through food access efforts – 97% of the harvest.", "classification": "Community Supported Agriculture"}
------
4 Historic Boggy Creek Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Our market offers a great variety of fruits & vegetables year-round, grown in fields just steps away, for the freshest farm to table experience!", "classification": ""}
------
5 Boggy Creek Farm Stand / Market
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Our market offers a great variety of fruits & vegetables year-round, grown in fields just steps away, for the freshest farm to table experience!", "classification": "farm stand/market"}
------
6 Rail Lily Farm
This message appears to be a Facebook message or notification from the account "Rain Lily Farm". The message is warning about someone selling a Toyota for $1800, claiming it's connected to the sender's sight, and asking if this is true. If so, they're willing to take the deal. If not, they suspect it's a scam.

Here are some key points from the message:

*   The account "Rain Lily Farm" is sending out an alert about someone selling a Toyota for $1800.
*   They're claiming that the price is suspiciously low and might be connected to their own sight.
*   If this is true, they'll take the deal.
------
7 Green Gate Farms
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Cultivating organic food and flowers, communities and farmers since 2006", "classification": ""}
------
8 PEAS Community Farm & Urban Orchard
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Everyone is welcome at PEAS Community Farm & Urban Orchard!Todos son bienvenidos en PEAS Granja comunitaria y huerto urbano!", "classification": ""}
------
9 812 Outdoor Market
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Mercado 812 está contratando para todas las posiciones de fin de semana a medio tiempo, con 8-10 horas por día.", "classification": "Flea Market" }
------
10 Arboretum Market
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
11 The Great Outdoors
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
12 Local Pastures
{
    "website_found": true,
    "is_farm": true,
    "acres_not_listed": false,
    "more_5_acres": false,
    "social_media_found": true,
    "sells_produce": "evidence found",
    "sells_only_flowers_or_honey": false,
    "evidence": "# Your local source for pasture-raised groceries.\n\nWe’ve made eating from local, regenerative farms in Central Texas easier than ever. Our products include:\n\nPasture Raised Pork\n\nPasture Raised Chicken\n\nPasture Raised Duck\n\nPasture Raised Eggs\n\nGrass Finished Beef\n\nProduce, Coffee, Honey, and more from other local producers and friends.\n\n",
    "classification": ""
}
------
13 Fair Market
{
    "website_found": true,
    "is_farm": false,
    "acres_not_listed": false,
    "more_5_acres": false,
    "social_media_found": true,
    "sells_produce": "evidence not found",
    "sells_only_flowers_or_honey": false,
    "evidence": "",
    "classification": ""
}
------
14 Gray Fox Market Garden
I apologize for the incomplete response earlier. Here's another attempt to start the research:

```
{
  "website_found": false,
  "is_farm": null,
  "acres_not_listed": null,
  "more_5_acres": null,
  "social_media_found": false,
  "sells_produce": null,
  "sells_only_flowers_or_honey": null,
  "evidence": "",
  "classification": ""
}
```

I couldn't find any useful information about the Gray Fox Market Garden farm without a provided website. Let me try searching for an official website or social media page to continue the research.
------
15 Tillery Street Plant Co.
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": false, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "We ship via USPS every week.", "classification": ""}
------
16 Sour Duck Market
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
17 Plant Party
**Potting Mat - Mess-Free Indoor Gardening**

Make gardening easier and cleaner with our durable and long-lasting repotting mat. Simply unroll the mat, clip the corners, and get to work! Once done, wipe down and store with our handy hanging ring.

**Size Options:**
- **Medium**: 29.5 X 19.6 Inches
- **Large**: 30" x 19"

**Made from recycled plastic**, this mat makes a great planty present and is perfect for indoor gardening.

**Features:**

*   Mess-free gardening with our durable repotting mat
*   Easy to clean and store with our handy hanging ring
*   Made from recycled plastic, eco-friendly and sustainable

**Get Your Repotting Mat Today!**
------
18 The Arboretum
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}}
------
19 Cosmic Pickle
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}}
------
20 Joe's Microgreens
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Our produce is never sprayed with chemicals or fed anything we wouldn’t serve to our own family.", "classification": ""}
------
21 Agua Dulce Austin
Agua Dulce Austin
{
  "website_found": false,
  "is_farm": true,
  "acres_not_listed": true,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence not found",
  "sells_only_flowers_or_honey": false,
  "evidence": "",
  "classification": ""
}
------
22 Brite Ideas - Aquaponics, Hydroponics & Organics
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
23 Brite Ideas Aquaponics, Hydroponics & Organics
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": false, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
24 Aquaflora on Evelyn
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "Join us in our mission to deliver fresh, premium produce to your table.",
  "classification": ""
}
------
25 Vertical Growing Systems LLC
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "We\u2019re scheduled to deliver our first order of edible plant panels this Fall. The nearly 100 square foot system will include a wide variety of cool season vegetables and herbs including spinach, Swiss chard, kale, snow peas, chives, onions, snap peas, mints, oregano, and many other varieties of lettuce and greens.", "classification": ""}
------
26 Native Roots Farm
{"website_found": false, "is_farm": true, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
27 BV Hydroseeding & Hydromulching
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
28 ATX GROWERS
According to the website at http://atxgrowers.com/, ATX GROWERS is a farm that sells produce through their community supported agriculture program. They have multiple locations throughout Austin, Texas.

{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Our farm is a small family-owned and operated farm that specializes in growing fresh produce for our CSA program.", "classification": ""}
------
29 UT Microfarm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "All produce goes directly to UT Outpost", "classification": "farm" }
------
30 OG Agave
The text you provided is not a coherent article or a post, but rather a snippet of HTML code from Instagram. It appears to be the metadata and links for an Instagram post about a succulent plant.

If you could provide more context or clarify what specific information or content you would like me to assist with, I would be happy to help in any way I can.
------
31 The Natural Gardener
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "\"Shop native and adapted plants, plus organic veggies, herbs, and more!\"", "classification": ""}
------
32 EDEN HOUSE BOTANICALS LLC
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
33 Biological Greenhouse (BOT)
{"website_found": false, "is_farm": false, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
34 Biological Sciences Greenhouses (BGH)
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": false, "sells_produce": "no evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
35 Green Planet Scapes of Austin
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
36 East Austin Succulents
{"website_found": true, "is_farm": false, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "no evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
37 Cypress Creek Farm
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "At Cypress Creek Farm, diverse ecosystems converge, and cultivate plants and produce that is beyond organic.", "classification": "Community Supported Agriculture"}
------
38 Sparkle Farm
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": true,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "We are proud to call Austin, TX home and look forward to all of the adventures these five acres have in store for us.",
  "classification": ""
}
------
39 Village Farm Tiny Home community
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence not found",
  "sells_only_flowers_or_honey": false,
  "evidence": "",
  "classification": ""
}
------
40 A Full Eco Farm for Group Stays
{"website_found": false, "is_farm": true, "acres_not_listed": true, "more_5_acres": false, "social_media_found": false, "sells_produce": "no evidence found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
41 Dan & Lou's! Fresh Microgreens
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "\"Don\\u2019t judge each day by the harvest that you reap, but by the seeds that you plant.\" – Robert Louis Stevenson\n\nView this post on Instagram\n\nA post shared by Dan & Lou's! Fresh Microgreens (@danandlousfreshmicrogreens)",
  "classification": ""
}
------
42 Verdivivo Microgreens
Since the website is missing, I will search for an official website or social media.

{"name": "web_search", "parameters": {"url":"https://www.google.com/search?q=Verdivivo+Microgreens+official+website"}}
------
43 Farmshare Austin
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "Get affordable, fresh food and healthy groceries delivered to your home. https://www.farmshareaustin.org/home-delivery",
  "classification": ""
}
------
44 Munkebo Farm
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "We have permanent 4' rows that are heavily mulched to keep down weeds and prevent water loss.",
  "classification": ""
}
------
45 Lady Bird Johnson Wildflower Center
This is a social media feed from the Wildflower Center in Austin, Texas. The center is a botanical garden and research institution that focuses on native plants and conservation.

The posts are about various topics related to the Wildflower Center, including:

* Native plants and their benefits
* Pollinator Week and how the center supports pollinators
* Summer solstice and seasonal changes
* Plant care tips for hot weather
* Upcoming events and programs

Some specific posts mention:

* Flame acanthus (Anisacanthus quadrifidus var. wrightii) as a favorite of hummingbirds, pollinators, and gardeners alike
* Sensitive briar (Mimosa roemeriana) as a Texas native with fascinating adaptations
* Summer rockstars: Eysenhardtia texana, Wedelia acapulcensis var. hispida, and Lantana urticoides
* The importance of protecting wild populations, including the Texas bluebell (Eustoma exaltatum ssp. russellianum)
* Behind-the-scenes looks at renovations and new projects, such as a custom mural inspired by the future pollinator garden

The posts are written in a friendly, conversational tone and include hashtags related to native plants, conservation, and the Wildflower Center.
------
46 Petals, ink.
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": true, "social_media_found": true, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "Order Seasonal Subscriptions or Local Flower Delivery Available Now\nOur arrangements are 100% locally grown on our flower farm in Manor, Texas.", "classification": "flower farm" }
------
47 In the Garden Farm
{"website_found": false, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
48 UT Farm Stand Jester Garden
{"name":"web_search","parameters":{"query":"UT Farm Stand Jester Garden website official social media",}}
------
49 Vital Farms
{
  "website_found": true,
  "is_farm": true,
  "acres_not_listed": false,
  "more_5_acres": false,
  "social_media_found": true,
  "sells_produce": "evidence found",
  "sells_only_flowers_or_honey": false,
  "evidence": "Our network of family farms gives them the lifestyle they deserve.",
  "classification": ""
}
------
50 Doonesbury Farm
{"website_found": false, "is_farm": true, "acres_not_listed": true, "more_5_acres": false, "social_media_found": true, "sells_produce": "evidence not found", "sells_only_flowers_or_honey": false, "evidence": "", "classification": ""}
------
51 South Grown Chicken Farm Elgin Texas
{"website_found": true, "is_farm": true, "acres_not_listed": false, "more_5_acres": false, "social_media_found": false, "sells_produce": "evidence found", "sells_only_flowers_or_honey": false, "evidence": "In the heart of every homesteader lies a spirit that thrives on hard work, connection to the land, and the pursuit of sustainability.", "classification": ""}
------
52 Coyote Creek Organic Feed Mill & Farm Store

In [ ]:
"""
sells produce and under 75*** and incorporated farm (Dallas)


Elmwood Farms
Joppy Momma's Farm
Hatcher Station Training Farm
Bonton Farms
Bonton Farms Extension
Eden's Organic Farm Center and CSA farm
New Life Farms
Gotham Greens Dallas
OHM Microgreens
Owenwood Farm & Neighbor Space
Pawpaws Produce & Co 
South Prarie Farm - Grand Prarie 
Urban Farm Co. by Dallas Urban Farms
Earth Healthy Farm 
Dallas Half Acre Farm
Liberty Street Garden
WE over Me Farm, at Paul Quinn College
Cultivated Chicks




"""

"\nUnder 5 and sells produce: \nElmwood Farms\nJoppy Momma's Farm\nHatcher Station Training Farm\n"

In [ ]:
"""
""
sells produce and under 75*** and incorporated farm (Travis)

Urban Roots East Austin Farm
Urban Roots South Austin Farm
HausBar Urban Farm
Historic Boggy Creek Farm
Green Gate Farms
Gray Fox Market Garden
Agua Dulce Austin
Aquaflora on Evelyn
Farmshare Austin
New Leaf Agriculture
Dragon City Farms
Gardeners in Community Development
Telecote Farm

"""

In [8]:
keep_names = [
    "Urban Roots East Austin Farm",
    "Urban Roots South Austin Farm",
    "HausBar Urban Farm",
    "Historic Boggy Creek Farm",
    "Green Gate Farms",
    "Gray Fox Market Garden",
    "Agua Dulce Austin",
    "Aquaflora on Evelyn",
    "Farmshare Austin",
    "New Leaf Agriculture",
    "Dragon City Farms",
    "Gardeners in Community Development",
    "Telecote Farm"
]

filtered_travis = travis_farms[
    travis_farms["name"].isin(keep_names)
].copy()

filtered_travis

,name,address,lat,lon,Website,Google Categories,Place ID,Status,profile_url,osm_id,...,LSADC,FUNCSTAT,COUNTYCC,AREALAND,AREAWATER,OBJECTID,CENTLAT,CENTLON,INTPTLAT,INTPTLON
0,Urban Roots East Austin Farm,"7651 Delwau Ln, Austin, TX 78725, USA",30.262875,-97.664225,http://www.urbanrootsatx.org/,"establishment, point_of_interest",ChIJa3zq91m2RIYRiQcwrsMaZVM,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HausBar Urban Farm,"3300 Govalle Ave, Austin, TX 78702, USA",30.265790,-97.700920,http://hausbarurbanfarm.com/,"establishment, point_of_interest",ChIJURTtlte1RIYRj_0fhij0FnY,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Urban Roots South Austin Farm,"4711 Winnebago Ln, Austin, TX 78744, USA",30.207336,-97.735117,https://urbanrootsatx.org/,"establishment, point_of_interest",ChIJ7dpUWwCzRIYR_8ya8brOPG0,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Historic Boggy Creek Farm,"3414 Lyons Rd, Austin, TX 78702, USA",30.261969,-97.701572,http://www.boggycreekfarm.com/,"establishment, lodging, point_of_interest",ChIJR9PUita1RIYR1FlipeiVMdU,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Green Gate Farms,"8310 Canoga Ave, Austin, TX 78724, USA",30.285460,-97.634809,https://greengatefarms.net/,"establishment, food, point_of_interest, store",ChIJCaFZ_SC3RIYRO80x3-ZLGTY,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Gray Fox Market Garden,"10802 Kit Carson Dr, Austin, TX 78737, USA",30.203346,-97.957245,Not listed,"establishment, point_of_interest",ChIJDXwqTqhIW4YRnJQKrS7jEaU,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Agua Dulce Austin,"5015 Maufrais Ln, Austin, TX 78744, USA",30.199026,-97.736973,Not listed,"establishment, point_of_interest",ChIJYa_bnIOzRIYR_1sR3bssC1Q,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Aquaflora on Evelyn,"7108 Evelyn Rd, Austin, TX 78747, USA",30.083217,-97.701344,https://www.aquafloraonevelyn.com/,"establishment, point_of_interest",ChIJ_-C1IACtRIYRwEMzjlvb6I4,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Farmshare Austin,"3608 River Rd, Cedar Creek, TX 78612, USA",30.197146,-97.511882,http://farmshareaustin.org/,"establishment, food, grocery_or_supermarket, p...",ChIJaRbuMW28RIYRQn-pviNGE40,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65,New Leaf Agriculture,NaN,30.270000,-97.740000,NaN,NaN,NaN,NaN,localharvest.org/new-leaf-agriculture-M80602,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
set(keep_names) - set(travis_farms["name"])

{'Dragon City Farms', 'Gardeners in Community Development', 'Telecote Farm'}

In [27]:
#append miscellaneous 
new_rows = pd.DataFrame([
    {
        "name": "Dragon City Farms",
        "address": "2435 Walnut Ridge Street",
        "lat": 32.8943,
        "lon": -96.8856,
        "Website": "https://dragoncityfarms.com",
    },
    {
        "name": "Gardeners in Community Development",
        "address": "901 Greenbriar Ln",
        "lat": 32.9554,
        "lon": -96.7456,
        "Website": "https://www.facebook.com/gardendallas/",
    },
    {
        "name": "Telcolote Farm",
        "address": "16301 Decker Lake Rd,",
        "lat": 30.25777345,
        "lon": -97.56395878,
        "Website": "http://www.tecolotefarm.net"
    }
])

In [28]:
travis_farms = pd.concat([farms, new_rows], ignore_index=True)

In [22]:
keep_names_2 = [
    "Elmwood Farm",
    "Joppy Momma's Farm",
    "Hatcher Station Training Farm",
    "Bonton Farms",
    "Bonton Farms Extension",
    "Eden's Organic Garden Center & CSA Farm",
    "Gotham Greens Seagoville",
    "OHM Microgreens",
    "Owenwood Farm & Neighbor Space",
    "Pawpaws Produce & Co",
    "South Prairie Farm",
    "Urban Farm Co. by Dallas Urban Farms",
    "Earth Healthy",
    "Dallas Half Acre Farm",
    "Liberty Street Garden, at The Meadows Foundation",
    "WE over Me Farm, at Paul Quinn College",
    "Cultivated Chicks"
]

filtered_dallas = farms[
    farms["name"].isin(keep_names_2)
].copy()

filtered_dallas

,name,address,lat,lon,Website,Google Categories,Place ID,Status,profile_url,osm_id,...,LSADC,FUNCSTAT,COUNTYCC,AREALAND,AREAWATER,OBJECTID,CENTLAT,CENTLON,INTPTLAT,INTPTLON
0,Elmwood Farm,"1014 Nolte Dr, Dallas, TX 75208, USA",32.733665,-96.839587,https://www.elmwoodfarm.co/,"establishment, point_of_interest",ChIJU0-cis2bToYRyZtlm5ZeI_o,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Joppy Momma's Farm,"7728 Carbondale St, Dallas, TX 75216, USA",32.716707,-96.750832,https://joppymommas.org/,"establishment, point_of_interest",ChIJ83XUCMSXToYRGSEJdqmd8Qo,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hatcher Station Training Farm,"4500 Todd St, Dallas, TX 75210, USA",32.766178,-96.744199,http://www.restorativefarms.org/,"establishment, point_of_interest",ChIJIUgpTvSjToYRBuHzeEgdWuw,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Bonton Farms,"6911 Bexar St, Dallas, TX 75215, USA",32.734735,-96.753758,http://bontonfarms.org/,"establishment, point_of_interest",ChIJn7-J6wuYToYRL2NAvMPqb8k,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Bonton Farms Extension,"12400 Ravenview Rd, Dallas, TX 75253, USA",32.694169,-96.603067,http://www.bontonfarms.org/,"establishment, point_of_interest",ChIJg91ZoOy6ToYRO4ne1iLt44A,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Eden's Organic Garden Center & CSA Farm,"4710 Pioneer Rd, Balch Springs, TX 75180, USA",32.705824,-96.605397,http://www.edensorganicgardencenter.com/,"establishment, point_of_interest, store",ChIJ45xm7cC6ToYRjG_NnSXH-Fs,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Gotham Greens Seagoville,"800 Environmental Way, Seagoville, TX 75159, USA",32.646028,-96.563552,https://www.gothamgreens.com/,"establishment, food, point_of_interest",ChIJA24ItduxToYRq4cIV-6Kv8w,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,OHM Microgreens,"5931 Greenville Ave PMB 3054, Dallas, TX 75206...",32.857840,-96.768916,https://ohmmicrogreens.com/,"establishment, point_of_interest",ChIJn1qHJmqfToYRfSBGcZ6MFGk,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Owenwood Farm & Neighbor Space,"1451 John West Rd, Dallas, TX 75228, USA",32.807326,-96.692913,http://www.owenwood.org/,"establishment, point_of_interest",ChIJGYwr_tijToYR1wY2UtF-5NI,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Pawpaws Produce & Co,"2220 E Ledbetter Dr, Dallas, TX 75216, USA",32.686718,-96.786526,Not listed,"establishment, point_of_interest",ChIJO_lTzoGXToYR4R0ZbTZr3Mg,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,South Prairie Farm,"4405 Sharpsburg Dr, Grand Prairie, TX 75052, USA",32.665709,-97.020526,http://www.southprairiefarm.com/,"establishment, point_of_interest",ChIJ1y4RAOKJToYRy0rMSIqhDpA,Pending Review,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,Urban Farm Co. by Dallas Urban Farms,"Location: 3939 South Polk Street #511 Dallas, ...",32.696869,-96.840586,NaN,NaN,NaN,NaN,localharvest.org/urban-farm-co-by-dallas-urban...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Earth Healthy,"Location: N Westmoreland Rd 2010 Desoto, TX 75115",32.628370,-96.874324,NaN,NaN,NaN,NaN,localharvest.org/earth-healthy-M72493,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Dallas Half Acre Farm,"13608 Fernheath Ln, Dallas, TX 75253",32.690724,-96.580581,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,"Liberty Street Garden, at The Meadows Foundation","510 Liberty St, Dallas, TX 75204",32.789016,-96.785638,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,"WE over Me Farm, at Paul Quinn College","3837 Simpson Stuart Rd, Dallas, Texas, 75241",32.680539,-96.751835,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,Cultivated Chicks,"1832 Glenn Lane, Glenn Heights, TX 75154",32.555558,-96.851558,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
filtered_dallas.to_csv("filtered_dallas_farms_final.csv", index=False)

In [24]:
set(keep_names_2) - set(farms["name"])

set()

In [29]:
dallas_farms = farms

In [30]:
travis_farms.to_csv("travis_farms.csv", index=False)
dallas_farms.to_csv("dallas_farms.csv", index=False)